# Generated by Django 4.2.11 on 2026-05-26 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kapster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('no_hp', models.CharField(blank=True, max_length=15, null=True)),
                ('status_aktif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Layanan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_layanan', models.CharField(max_length=100)),
                ('harga', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PesananBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pelanggan', models.CharField(max_length=100)),
                ('no_whatsapp', models.CharField(max_length=20)),
                ('tanggal', models.DateField()),
                ('jam_booking', models.CharField(max_length=10)),
                ('total_harga', models.IntegerField(default=0)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('kapster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.kapster')),
                ('layanan', models.ManyToManyField(to='booking.layanan')),
            ],
        ),
    ]
